
Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [6]:
import numpy as np

vec = np.arange(1, 21)
print(vec)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [7]:
import numpy as np

mat_ones = np.ones((4, 4), dtype=int)
print(mat_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [8]:
import numpy as np

array = np.random.uniform(-1, 1, size=(5, 5))
print(array)

[[-0.18351876  0.5885263   0.15293528  0.35836552 -0.56668805]
 [-0.94626351  0.64474117 -0.69454544 -0.37268976  0.67087852]
 [ 0.50822164  0.34954947  0.93962083 -0.82983674 -0.86821905]
 [ 0.26601518 -0.21163246 -0.98867586 -0.10625231 -0.03909526]
 [ 0.14604998 -0.54604891  0.1292857   0.99377386 -0.92477372]]


Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [9]:
import numpy as np

array = np.random.random((3, 3))
print(array)

[[0.80268045 0.63868188 0.24302996]
 [0.39280741 0.84283673 0.86932511]
 [0.02199961 0.13121516 0.64671449]]


Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [10]:
import numpy as np

a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)

a = [20  8  1 11  4 12]
b = [ 9 13  1 17 17 17]
a + b = [29 21  2 28 21 29]
a - b = [ 11  -5   0  -6 -13  -5]
a * b = [180 104   1 187  68 204]


Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [11]:
import numpy as np

m1 = np.random.randint(1, 6, size=(3, 2))
m2 = np.random.randint(1, 6, size=(2, 4))

prod = m1 @ m2

print("m1:", m1)
print("m2:", m2)
print("m1 @ m2:", prod)

m1: [[2 3]
 [4 4]
 [4 5]]
m2: [[5 4 1 5]
 [4 1 4 1]]
m1 @ m2: [[22 11 14 13]
 [36 20 20 24]
 [40 21 24 25]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [12]:
import numpy as np

m = np.random.random((3, 3))
mt = m.T

print("m:", m)
print("m.T:", mt)

m: [[0.15703502 0.98054352 0.46775379]
 [0.42677164 0.53915212 0.55094654]
 [0.33650118 0.8858222  0.41739041]]
m.T: [[0.15703502 0.42677164 0.33650118]
 [0.98054352 0.53915212 0.8858222 ]
 [0.46775379 0.55094654 0.41739041]]


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [13]:
import numpy as np

x = np.random.randint(1, 11, size=(3, 3))
y = np.random.randint(1, 11, size=(3, 3))

diff = x - y

print("x:", x)
print("y:", y)
print("x - y:", diff)

x: [[10  2  6]
 [ 8  1  6]
 [ 6  1  9]]
y: [[6 8 9]
 [2 6 6]
 [7 3 9]]
x - y: [[ 4 -6 -3]
 [ 6 -5  0]
 [-1 -2  0]]


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [14]:
import numpy as np

p = np.random.randint(-5, 6, size=(3, 3))
q = np.random.randint(-5, 6, size=(3, 3))

elem_prod = p * q

print("p:", p)
print("q:", q)
print("p * q:", elem_prod)

p: [[-2  1  3]
 [ 1  5  2]
 [ 2 -1  2]]
q: [[-5 -4 -5]
 [-5 -4  3]
 [-5  3  5]]
p * q: [[ 10  -4 -15]
 [ -5 -20   6]
 [-10  -3  10]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [15]:
import numpy as np

m = np.random.uniform(-1, 1, size=(3, 3))
row_sums_col = m.sum(axis=1).reshape(-1, 1)

print("m:", m)
print("row sums:", row_sums_col)

m: [[ 0.39611647  0.31852571 -0.75103925]
 [-0.3626511  -0.66126442 -0.24242515]
 [ 0.70160058  0.82715447  0.40645249]]
row sums: [[-0.03639706]
 [-1.26634067]
 [ 1.93520754]]
